# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="rollhax"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export EDITOR=vim

# auto-complete
autoload -U compinit
compinit

export EDITOR=nano
export PATH=$PATH:/home/dusty/bin

# aliases
alias dfh='df -h'
alias dircount='ls -l | wc -l'
alias dircountall='ls -al | wc -l'
alias dush='du -sh'
alias grep='grep --color=auto -i'
alias greppy='grep -niRE --color=auto'
alias l.='ls -d .*'
alias ll='ls -l'
alias ls='ls --color=auto'
alias mountiso='sudo mount -o loop -t iso9660'
alias mountntfs='sudo mount -t ntfs -o nls=utf8,umask=0222'
alias qlogic_vpn='sudo openconnect qlacmn.qlogic.com'
alias vmdjerome='rdesktop -D -K -g 1920x1080 -u djerome -d QLOGIC vmdjerome'
alias djeromessh='ssh djerome@djerome-linux'

# tmux aliases
alias tm2='tmux -2'
alias tmls='tmux ls'
alias tmat='tmux at'
alias tmatt='tmux at -t'
alias tmnew='tmux new -s'
